In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime
import seaborn as sns

In [2]:
riders = pd.read_csv('Riders.csv')
Sample_Submission = pd.read_csv('SampleSubmission.csv')
Test = pd.read_csv('Test.csv')
Train = pd.read_csv('Train.csv')
Variable_Def = pd.read_csv('VariableDefinitions.csv')

In [3]:
Train.head(10)

Order No       User Id Vehicle Type  Platform Type  \
0   Order_No_4211   User_Id_633         Bike              3   
1  Order_No_25375  User_Id_2285         Bike              3   
2   Order_No_1899   User_Id_265         Bike              3   
3   Order_No_9336  User_Id_1402         Bike              3   
4  Order_No_27883  User_Id_1737         Bike              1   
5   Order_No_7408  User_Id_1342         Bike              3   
6  Order_No_22680  User_Id_2803         Bike              3   
7  Order_No_21578  User_Id_1075         Bike              3   
8   Order_No_5234   User_Id_733         Bike              3   
9   Order_No_1768  User_Id_2112         Bike              3   

  Personal or Business  Placement - Day of Month  \
0             Business                         9   
1             Personal                        12   
2             Business                        30   
3             Business                        15   
4             Personal                        13   
5             Business                        14   
6             Business                         9   
7             Business                        11   
8             Business                        30   
9             Business                        23   

   Placement - Weekday (Mo = 1) Placement - Time  Confirmation - Day of Month  \
0                             5       9:35:46 AM                            9   
1                             5      11:16:16 AM                           12   
2                             2      12:39:25 PM                           30   
3                             5       9:25:34 AM                           15   
4                             1       9:55:18 AM                           13   
5                             5       3:07:35 PM                           14   
6                             5       9:33:45 AM                            9   
7                             1       2:13:01 PM                           11   
8                             2      11:10:44 AM                           30   
9                             5       4:48:54 PM                           23   

   Confirmation - Weekday (Mo = 1)  ... Arrival at Destination - Time  \
0                                5  ...                   10:39:55 AM   
1                                5  ...                   12:17:22 PM   
2                                2  ...                    1:00:38 PM   
3                                5  ...                   10:05:27 AM   
4                                1  ...                   10:25:37 AM   
5                                5  ...                    4:23:41 PM   
6                                5  ...                   10:19:45 AM   
7                                1  ...                    2:33:26 PM   
8                                2  ...                    1:19:35 PM   
9                                5  ...                    6:31:57 PM   

   Distance (KM)  Temperature Precipitation in millimeters  Pickup Lat  \
0              4         20.4                          NaN   -1.317755   
1             16         26.4                          NaN   -1.351453   
2              3          NaN                          NaN   -1.308284   
3              9         19.2                          NaN   -1.281301   
4              9         15.4                          NaN   -1.266597   
5              9         27.2                          NaN   -1.302583   
6              5         20.3                          NaN   -1.279395   
7              3         28.7                          NaN   -1.252796   
8              9          NaN                          NaN   -1.255189   
9             14         24.6                          NaN   -1.225322   

   Pickup Long Destination Lat  Destination Long      Rider Id  \
0    36.830370       -1.300406         36.829741  Rider_Id_432   
1    36.899315       -1.295004         36.814358  Rider_Id_856   
2    36.843419       -1.300921   

In [4]:
Test.head(10)

Order No       User Id Vehicle Type  Platform Type  \
0  Order_No_19248  User_Id_3355         Bike              3   
1  Order_No_12736  User_Id_3647         Bike              3   
2    Order_No_768  User_Id_2154         Bike              3   
3  Order_No_15332  User_Id_2910         Bike              3   
4  Order_No_21373  User_Id_1205         Bike              3   
5  Order_No_14573  User_Id_2338         Bike              1   
6   Order_No_6731   User_Id_488         Bike              2   
7  Order_No_18436  User_Id_3764         Bike              3   
8   Order_No_2288  User_Id_2866         Bike              3   
9   Order_No_9063  User_Id_1329         Bike              3   

  Personal or Business  Placement - Day of Month  \
0             Business                        27   
1             Business                        17   
2             Business                        27   
3             Business                        17   
4             Business                        11   
5             Personal                        13   
6             Personal                        17   
7             Business                        28   
8             Business                        28   
9             Business                         4   

   Placement - Weekday (Mo = 1) Placement - Time  Confirmation - Day of Month  \
0                             3       4:44:10 PM                           27   
1                             5      12:57:35 PM                           17   
2                             4      11:08:14 AM                           27   
3                             1       1:51:35 PM                           17   
4                             2      11:30:28 AM                           11   
5                             1       6:29:29 PM                           13   
6                             3       9:53:29 AM                           17   
7                             4       8:51:13 AM                           28   
8                             4       8:58:21 AM                           28   
9                             5       4:28:28 PM                            4   

   Confirmation - Weekday (Mo = 1)  ... Pickup - Weekday (Mo = 1)  \
0                                3  ...                         3   
1                                5  ...                         5   
2                                4  ...                         4   
3                                1  ...                         1   
4                                2  ...                         2   
5                                1  ...                         1   
6                                3  ...                         3   
7                                4  ...                         4   
8                                4  ...                         4   
9                                5  ...                         5   

   Pickup - Time  Distance (KM) Temperature  Precipitation in millimeters  \
0     5:06:47 PM              8         NaN                           NaN   
1     1:25:37 PM              5         NaN                           NaN   
2    11:57:54 AM              5        22.8                           NaN   
3     2:16:52 PM              5        24.5                           NaN   
4    11:56:04 AM              6        24.4                           NaN   
5     6:39:02 PM             16        19.3                           NaN   
6    10:08:00 AM             18        20.9                           NaN   
7     8:58:53 AM              8        22.7                           NaN   
8     9:30:35 AM              8        19.4                           NaN   
9     4:44:01 PM             15        21.7                           NaN   

   Pickup Lat Pickup Long  Destination Lat  Destination Long      Rider Id  
0   -1.333275   36.870815        -1.305249         36.822390  Rider_Id_192  
1   -1.272639   36.794723        -1.277007         36.823907  Rider_Id_868  
2   -1.2908

In [ ]:
Sample_Submission.head()

## Concatenate , drop and fill in missing values

In [3]:
data= pd.concat([Train,Test],sort=False)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 7067
Data columns (total 29 columns):
Order No                                     28269 non-null object
User Id                                      28269 non-null object
Vehicle Type                                 28269 non-null object
Platform Type                                28269 non-null int64
Personal or Business                         28269 non-null object
Placement - Day of Month                     28269 non-null int64
Placement - Weekday (Mo = 1)                 28269 non-null int64
Placement - Time                             28269 non-null object
Confirmation - Day of Month                  28269 non-null int64
Confirmation - Weekday (Mo = 1)              28269 non-null int64
Confirmation - Time                          28269 non-null object
Arrival at Pickup - Day of Month             28269 non-null int64
Arrival at Pickup - Weekday (Mo = 1)         28269 non-null int64
Arrival at Pickup - Time    

In [4]:
data['Arrival at Destination - Day of Month'] =data['Arrival at Destination - Day of Month'].fillna(data['Arrival at Destination - Day of Month'].median())
data['Arrival at Destination - Weekday (Mo = 1)'] = data['Arrival at Destination - Weekday (Mo = 1)'].fillna(data['Arrival at Destination - Weekday (Mo = 1)'].median())
data['Arrival at Destination - Time'] = data['Arrival at Destination - Time'].fillna(data['Arrival at Destination - Time'].mode())
data['Temperature'] = data['Temperature'].fillna(data['Temperature'].mean())
data['Time from Pickup to Arrival'] = data['Time from Pickup to Arrival'].fillna(data['Time from Pickup to Arrival'].mean())


In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 7067
Data columns (total 29 columns):
Order No                                     28269 non-null object
User Id                                      28269 non-null object
Vehicle Type                                 28269 non-null object
Platform Type                                28269 non-null int64
Personal or Business                         28269 non-null object
Placement - Day of Month                     28269 non-null int64
Placement - Weekday (Mo = 1)                 28269 non-null int64
Placement - Time                             28269 non-null object
Confirmation - Day of Month                  28269 non-null int64
Confirmation - Weekday (Mo = 1)              28269 non-null int64
Confirmation - Time                          28269 non-null object
Arrival at Pickup - Day of Month             28269 non-null int64
Arrival at Pickup - Weekday (Mo = 1)         28269 non-null int64
Arrival at Pickup - Time    

In [6]:
data_dropped=data.drop(['Precipitation in millimeters','User Id','Vehicle Type','Personal or Business','Placement - Day of Month','Placement - Weekday (Mo = 1)','Placement - Time','Confirmation - Day of Month','Confirmation - Weekday (Mo = 1)','Confirmation - Time','Arrival at Pickup - Day of Month','Arrival at Pickup - Weekday (Mo = 1)','Arrival at Pickup - Time','Pickup - Weekday (Mo = 1)','Arrival at Destination - Weekday (Mo = 1)','Arrival at Destination - Day of Month','Pickup Lat','Pickup Long','Destination Lat','Destination Long'],axis=1)

In [7]:
data_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 7067
Data columns (total 9 columns):
Order No                         28269 non-null object
Platform Type                    28269 non-null int64
Pickup - Day of Month            28269 non-null int64
Pickup - Time                    28269 non-null object
Arrival at Destination - Time    21202 non-null object
Distance (KM)                    28269 non-null int64
Temperature                      28269 non-null float64
Rider Id                         28269 non-null object
Time from Pickup to Arrival      28269 non-null float64
dtypes: float64(2), int64(3), object(4)
memory usage: 2.2+ MB


#### Changing the data type of time

In [8]:
data_dropped['Arrival at Destination - Time'] = pd.to_datetime(data_dropped['Arrival at Destination - Time'])
data_dropped['Pickup - Time'] = pd.to_datetime(data_dropped['Pickup - Time'])

In [9]:
data_dropped['Arrival at Destination - Time'] = data_dropped['Arrival at Destination - Time'].fillna(data_dropped['Arrival at Destination - Time'].mode()[0])

In [10]:
data_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 7067
Data columns (total 9 columns):
Order No                         28269 non-null object
Platform Type                    28269 non-null int64
Pickup - Day of Month            28269 non-null int64
Pickup - Time                    28269 non-null datetime64[ns]
Arrival at Destination - Time    28269 non-null datetime64[ns]
Distance (KM)                    28269 non-null int64
Temperature                      28269 non-null float64
Rider Id                         28269 non-null object
Time from Pickup to Arrival      28269 non-null float64
dtypes: datetime64[ns](2), float64(2), int64(3), object(2)
memory usage: 2.2+ MB


In [11]:
ty = data_dropped['Arrival at Destination - Time'].mode()
ty[0]

Timestamp('2020-05-21 15:24:03')

In [35]:
data_drop2 = data_dropped.drop(['Order No'],axis=1)
data_drop2.head()

Platform Type  Pickup - Day of Month       Pickup - Time  \
0              3                      9 2020-05-21 10:27:30   
1              3                     12 2020-05-21 11:44:09   
2              3                     30 2020-05-21 12:53:03   
3              3                     15 2020-05-21 09:43:06   
4              1                     13 2020-05-21 10:05:23   

  Arrival at Destination - Time  Distance (KM)  Temperature      Rider Id  \
0           2020-05-21 10:39:55              4    20.400000  Rider_Id_432   
1           2020-05-21 12:17:22             16    26.400000  Rider_Id_856   
2           2020-05-21 13:00:38              3    23.255689  Rider_Id_155   
3           2020-05-21 10:05:27              9    19.200000  Rider_Id_855   
4           2020-05-21 10:25:37              9    15.400000  Rider_Id_770   

   Time from Pickup to Arrival  
0                        745.0  
1                       1993.0  
2                        455.0  
3                       1341.0  
4                       1214.0

## Changing the datetime to be represented in seconds

In [46]:
data_drop2['Arrival at Destination - Time'] = data_drop2['Arrival at Destination - Time'].values.astype(np.int64)//10**9
data_drop2['Pickup - Time'] = data_drop2['Pickup - Time'].values.astype(np.int64)//10**9
data_drop2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 7067
Data columns (total 8 columns):
Platform Type                    28269 non-null int64
Pickup - Day of Month            28269 non-null int64
Pickup - Time                    28269 non-null int64
Arrival at Destination - Time    28269 non-null int64
Distance (KM)                    28269 non-null int64
Temperature                      28269 non-null float64
Rider Id                         28269 non-null int32
Time from Pickup to Arrival      28269 non-null float64
dtypes: float64(2), int32(1), int64(5)
memory usage: 2.5 MB


## Checking how many unique id's there are in an attempt to group them

In [58]:
dre = data_drop2.groupby('Rider Id')['Temperature'].nunique()
print(dre[dre<20])

Rider Id
Rider_Id_0       1
Rider_Id_1       1
Rider_Id_104     2
Rider_Id_106    10
Rider_Id_109     8
Rider_Id_11      9
Rider_Id_110     4
Rider_Id_113     2
Rider_Id_115     1
Rider_Id_117     3
Rider_Id_118    16
Rider_Id_12     17
Rider_Id_120    15
Rider_Id_121     1
Rider_Id_122     2
Rider_Id_123    17
Rider_Id_125    15
Rider_Id_128     5
Rider_Id_129     4
Rider_Id_13      1
Rider_Id_130    15
Rider_Id_132     7
Rider_Id_133     5
Rider_Id_134     6
Rider_Id_135     2
Rider_Id_136     9
Rider_Id_138    13
Rider_Id_14     11
Rider_Id_141     1
Rider_Id_142     1
                ..
Rider_Id_92     12
Rider_Id_920    16
Rider_Id_922     1
Rider_Id_923     8
Rider_Id_924     1
Rider_Id_927    11
Rider_Id_929     8
Rider_Id_93      2
Rider_Id_930    10
Rider_Id_931    16
Rider_Id_934     2
Rider_Id_935    10
Rider_Id_936    12
Rider_Id_938    10
Rider_Id_94      1
Rider_Id_940    10
Rider_Id_941     6
Rider_Id_943     7
Rider_Id_944     1
Rider_Id_945     1
Rider_Id_946    13
Rid

## Chose to represent the Id's as integer values instead so the model can detect them

In [42]:
data_drop2['Rider Id'] = data_drop2['Rider Id'].str.split('_').str[2]
data_drop2['Rider Id'] = data_drop2['Rider Id'].astype(int)

In [43]:
data_drop2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 7067
Data columns (total 8 columns):
Platform Type                    28269 non-null int64
Pickup - Day of Month            28269 non-null int64
Pickup - Time                    28269 non-null datetime64[ns]
Arrival at Destination - Time    28269 non-null datetime64[ns]
Distance (KM)                    28269 non-null int64
Temperature                      28269 non-null float64
Rider Id                         28269 non-null int32
Time from Pickup to Arrival      28269 non-null float64
dtypes: datetime64[ns](2), float64(2), int32(1), int64(3)
memory usage: 2.5 MB


In [54]:
data_drop3 = data_drop2.drop(['Arrival at Destination - Time'],axis=1)
data_drop3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 7067
Data columns (total 7 columns):
Platform Type                  28269 non-null int64
Pickup - Day of Month          28269 non-null int64
Pickup - Time                  28269 non-null int64
Distance (KM)                  28269 non-null int64
Temperature                    28269 non-null float64
Rider Id                       28269 non-null int32
Time from Pickup to Arrival    28269 non-null float64
dtypes: float64(2), int32(1), int64(4)
memory usage: 2.2 MB


## Using the random forest. Just trying it out

# creating x and y

In [63]:
X = data_drop2.iloc[:,:-1].values
y = data_drop2.iloc[:,-1].values
print(X)

[[3.00e+00 9.00e+00 1.59e+09 ... 4.00e+00 2.04e+01 4.32e+02]
 [3.00e+00 1.20e+01 1.59e+09 ... 1.60e+01 2.64e+01 8.56e+02]
 [3.00e+00 3.00e+01 1.59e+09 ... 3.00e+00 2.33e+01 1.55e+02]
 ...
 [3.00e+00 5.00e+00 1.59e+09 ... 1.00e+01 2.51e+01 3.79e+02]
 [3.00e+00 2.90e+01 1.59e+09 ... 1.80e+01 2.36e+01 4.74e+02]
 [3.00e+00 4.00e+00 1.59e+09 ... 8.00e+00 2.23e+01 7.60e+01]]


## Splitting test and training set

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## training random forest regression set

In [65]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

# Predicting y

In [66]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1556.92 1556.92]
 [1556.92 1556.92]
 [1556.92 1556.92]
 ...
 [1556.92 1556.92]
 [1397.5  1023.  ]
 [ 931.7   783.  ]]


# Evaluating model

In [67]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.859833585031091

In [69]:
from sklearn.metrics import mean_squared_error 
from math import sqrt

mse = sqrt(mean_squared_error(y_test,y_pred))
print(mse)

321.80048114775474
